services:
  postgres:
    image: postgres:latest
    container_name: bgo-postgres-db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: bgo-data
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - pg-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - '8080:80'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - pg-network

volumes:
  postgres-data:
  pgadmin-data:

networks:
  pg-network:
    driver: bridge