type Query {
  books: [Book]
  createEvent(input: CreateEventInput!): Event
  readEvent(input: ReadEventInput!): Event
  listEvents(input: ListEventsInput): [Event]
}

type Mutation {
  addBook(title: String, author: String): AddBookMutationResponse
  createEvent(input: CreateEventInput!): Event
  updateEvent(input: UpdateEventInput!): Event
  deleteEvent(input: DeleteEventInput!): EventDeletionResult
}

type Book {
  title: String
  author: String
}

type AddBookMutationResponse {
  code: String!
  success: Boolean!
  message: String!
  book: Book
}

type MutationResponse {
  code: String!
  success: Boolean!
  message: String!
}

input CreateEventInput {
  name: String!
  description: String
  proposedDatetime: String
  location: String
  imagePath: String
}

input UpdateEventInput {
  id: ID!
  name: String!
  description: String
  proposedDatetime: String
  location: String
  imagePath: String
}

input DeleteEventInput {
  id: ID!
}

input ReadEventInput {
  id: ID!
}

input ListEventsInput {
  pageSize: Int
  lastShownId: String
  showEventsOwnedByOthers: Boolean
}

type Event {
  id: ID!
  name: String!
  description: String
  proposedDatetime: String
  location: String
  createdTimestamp: String
  updatedTimestamp: String
  playedTimestamp: String
  imagePath: String
}

type EventDeletionResult {
  id: ID!
  deleteRequestTimestamp: String!
}